---
openapi: 3.0.1
info:
  title: Bloggit V1
  version: v1
paths:
  "/blogs/":
    get:
      summary: List all published blogs
      tags:
      - Admin
      - Normal User
      parameters:
      - name: search
        in: query
        description: Search term of filtering blogs
        schema:
          type: string
      - name: page
        in: query
        description: Page number of pagination
        minimum: 1
        schema:
          type: integer
      responses:
        '200':
          description: Returns a list of published blogs
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        title:
                          type: string
                        content:
                          type: string
                      required:
                      - id
                      - title
                      - content
                  meta:
                    type: object
                    properties:
                      current_page:
                        type: integer
                      total_pages:
                        type: integer
                      total_count:
                        type: integer
                    required:
                    - current_page
                    - total_pages
                    - total_count
                required:
                - data
                - meta
        '404':
          description: Page Overflow Error
        '400':
          description: Invalid Page Number
    post:
      summary: Create a new blog
      tags:
      - Admin
      parameters: []
      responses:
        '201':
          description: Blog created successfully
        '422':
          description: Blog creation failed
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                blog:
                  type: object
                  properties:
                    title:
                      type: string
                    content:
                      type: string
                    archived:
                      type: boolean
                    published_at:
                      type: string
                      format: date-time
                  required:
                  - title
                  - content
              required:
              - blog
  "/blogs/scheduled":
    get:
      summary: List all scheduled blogs
      tags:
      - Admin
      responses:
        '200':
          description: Returns a list of scheduled blogs
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        title:
                          type: string
                        content:
                          type: string
                      required:
                      - id
                      - title
                      - content
                  meta:
                    type: object
                    properties:
                      current_page:
                        type: integer
                      total_pages:
                        type: integer
                      total_count:
                        type: integer
                    required:
                    - current_page
                    - total_pages
                    - total_count
                required:
                - data
                - meta
        '404':
          description: Page Overflow Error
        '400':
          description: Invalid Page Number
  "/blogs/draft":
    get:
      summary: List all draft blogs
      tags:
      - Admin
      responses:
        '200':
          description: Returns a list of draft blogs
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        title:
                          type: string
                        content:
                          type: string
                      required:
                      - id
                      - title
                      - content
                  meta:
                    type: object
                    properties:
                      current_page:
                        type: integer
                      total_pages:
                        type: integer
                      total_count:
                        type: integer
                    required:
                    - current_page
                    - total_pages
                    - total_count
                required:
                - data
                - meta
        '404':
          description: Page Overflow Error
        '400':
          description: Invalid Page Number
  "/blogs/archived":
    get:
      summary: List all archived blogs
      tags:
      - Admin
      responses:
        '200':
          description: Returns a list of archived blogs
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        title:
                          type: string
                        content:
                          type: string
                      required:
                      - id
                      - title
                      - content
                  meta:
                    type: object
                    properties:
                      current_page:
                        type: integer
                      total_pages:
                        type: integer
                      total_count:
                        type: integer
                    required:
                    - current_page
                    - total_pages
                    - total_count
                required:
                - data
                - meta
        '404':
          description: Page Overflow Error
        '400':
          description: Invalid Page Number
  "/blogs/{id}":
    get:
      summary: Show a blog
      tags:
      - Admin
      - Normal User
      parameters:
      - name: id
        in: path
        description: Blog ID
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Returns a blog
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  content:
                    type: string
                required:
                - id
                - title
                - content
        '404':
          description: blog not found
        '406':
          description: unsupported accept header
    put:
      summary: Update a blog
      tags:
      - Admin
      parameters:
      - name: id
        in: path
        description: Blog ID
        required: true
        schema:
          type: integer
      responses:
        '202':
          description: Blog updated successfully
        '422':
          description: Blog update failed
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                blog:
                  type: object
                  properties:
                    title:
                      type: string
                    content:
                      type: string
                    archived:
                      type: boolean
                    published_at:
                      type: string
                      format: date-time
                  required:
                  - title
                  - content
              required:
              - blog
  "/blogs/{id}/archive":
    parameters:
    - name: id
      in: path
      description: Blog ID
      required: true
      schema:
        type: integer
    patch:
      summary: Archive a blog
      tags:
      - Admin
      responses:
        '202':
          description: Blog archived successfully
        '422':
          description: Blog archive failed
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: http://localhost:3000
